#Jekyll config file

name: Laurensius Jeffrey Chandra
description: "Social Media Addict, Writer, open source developer"
author: Laurensius Jeffrey Chandra
gravatar_id: 92ce146fe7bba637cb0629582e2ba91b
job_title: Owner
employer: No-Logic Design
url: "https://blog.arcestia.my.id"
location:
  city: Jakarta
  state: Jakarta
  country: Republic of Indonesia
ga_username: "UA-68555939-1"
twitter:
  username: "@LizSnowy"
  account_id: "356648632"
google_plus_id: LaurensiusJeffreyChandra
branch: master

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - test
  - less
  - scss
  - media
  - feature-detects
  - composer.json
  - component.json
  - grunt.js
  - assets/vendor/bootstrap-sass/stylesheets
  - assets/vendor/font-awesome/less
  - assets/vendor/font-awesome/scss
  - assets/vendor/font-awesome/src
  - assets/vendor/modernizr/feature-detects
  - assets/vendor/modernizr/media
  - assets/vendor/modernizr/test
  - assets/vendor/anchor-js/index.html
  - ".bundle"
  - vendor
  - node_modules

#number of items in RSS feed
rss_limit: 10

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/

# Frontmatter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

#disqus widget
disqus:
  shortname: 'arcestia'
  count: 5
  api_key: "gy7BKcBNNp58VBQMCbi7Fdm0o3JSSbcvu0m4LBUWmRrhkrJaQrVxNQaNj2sC4dg1"

#build config
highlighter: pygments
markdown: kramdown
timezone: Asia/Jakarta
encoding: UTF-8

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: :compressed
