url: ""

proofer:
  href_ignore:
    - "#comments"
    - !ruby/regexp '/https?:\/\/(www)?\.youtube\.com\/watch\?v=.*/i'
  check_html: true

github:
  repository_nwo: "arcestia/arcestia.github.io"
  owner_url: "https://github.com/arcestia"

ra11y:
  standard: Section508
  level: error
